# Generated by Django 5.0.9 on 2024-11-14 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_contentsection_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentsection',
            name='title',
        ),
    ]
