# Generated by Django 5.0.9 on 2024-11-14 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_contentsection_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsection',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.page'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.page'),
        ),
    ]
