# Generated by Django 5.0.9 on 2024-11-15 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_page_created_at_alter_page_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='thumbnail',
        ),
    ]
