# Generated by Django 5.0.9 on 2024-11-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_galleryimage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='gallery_images/thumbnails/'),
        ),
    ]
